import {
  AccessProfile,
  Collaborator,
  Survey,
  InterviewSubmission,
  RecentConnection,
  ExternalImport,
  ActionAuditLog,
} from './types';

export const initialProfiles: AccessProfile[] = [
  {
    id: 'prof_admin',
    name: 'Administrador Master',
    description: 'Acesso irrestrito a todos os módulos, configurações, exclusões e edições de respostas.',
    permissions: {
      colaboradores_alterar_senha: true,
      colaboradores_desativar: true,
      colaboradores_editar: true,
      colaboradores_acesso: true,
      colaboradores_incluir: true,

      analise_acesso: true,
      analise_criar_alterar_excluir_resposta: true,

      importacao_importar_planilha: true,
      importacao_excluir: true,
      importacao_acesso: true,

      meta_criar_alterar_excluir: true,
      meta_acesso: true,

      pesquisa_visualizar_excluidas: true,
      pesquisa_acesso: true,
      pesquisa_criar: true,
      pesquisa_alterar: true,
      pesquisa_excluir: true,
      pesquisa_ouvir_audio: true,
      pesquisa_visualizar_georeferenciamento: true,
      pesquisa_exportar_resultados: true,
      pesquisa_visualizar_inativas: true,
      pesquisa_replicar: true,
      pesquisa_desativar: true,
      pesquisa_acessa_todas_sem_associacao: true,
      pesquisa_alteracao_resposta_espontanea: true,

      respostas_acesso: true,
      respostas_alterar: true,

      home_acesso: true,
      home_visualiza_paineis_superiores: true,
      home_visualiza_conexoes_recentes: true,

      politicas_acesso: true,
    },
  },
  {
    id: 'prof_coord',
    name: 'Coordenador de Campo',
    description: 'Gerencia pesquisadores, pesquisas ativas e visualiza respostas e metas.',
    permissions: {
      colaboradores_alterar_senha: false,
      colaboradores_desativar: false,
      colaboradores_editar: true,
      colaboradores_acesso: true,
      colaboradores_incluir: true,

      analise_acesso: true,
      analise_criar_alterar_excluir_resposta: false,

      importacao_importar_planilha: true,
      importacao_excluir: false,
      importacao_acesso: true,

      meta_criar_alterar_excluir: true,
      meta_acesso: true,

      pesquisa_visualizar_excluidas: false,
      pesquisa_acesso: true,
      pesquisa_criar: true,
      pesquisa_alterar: true,
      pesquisa_excluir: false,
      pesquisa_ouvir_audio: true,
      pesquisa_visualizar_georeferenciamento: true,
      pesquisa_exportar_resultados: true,
      pesquisa_visualizar_inativas: true,
      pesquisa_replicar: true,
      pesquisa_desativar: true,
      pesquisa_acessa_todas_sem_associacao: false,
      pesquisa_alteracao_resposta_espontanea: false,

      respostas_acesso: true,
      respostas_alterar: false,

      home_acesso: true,
      home_visualiza_paineis_superiores: true,
      home_visualiza_conexoes_recentes: true,

      politicas_acesso: false,
    },
  },
  {
    id: 'prof_pesq',
    name: 'Pesquisador de Campo',
    description: 'Coleta entrevistas em campo e acessa formulários vinculados.',
    permissions: {
      colaboradores_alterar_senha: false,
      colaboradores_desativar: false,
      colaboradores_editar: false,
      colaboradores_acesso: false,
      colaboradores_incluir: false,

      analise_acesso: false,
      analise_criar_alterar_excluir_resposta: false,

      importacao_importar_planilha: false,
      importacao_excluir: false,
      importacao_acesso: false,

      meta_criar_alterar_excluir: false,
      meta_acesso: true,

      pesquisa_visualizar_excluidas: false,
      pesquisa_acesso: true,
      pesquisa_criar: false,
      pesquisa_alterar: false,
      pesquisa_excluir: false,
      pesquisa_ouvir_audio: false,
      pesquisa_visualizar_georeferenciamento: false,
      pesquisa_exportar_resultados: false,
      pesquisa_visualizar_inativas: false,
      pesquisa_replicar: false,
      pesquisa_desativar: false,
      pesquisa_acessa_todas_sem_associacao: false,
      pesquisa_alteracao_resposta_espontanea: false,

      respostas_acesso: false,
      respostas_alterar: false,

      home_acesso: true,
      home_visualiza_paineis_superiores: false,
      home_visualiza_conexoes_recentes: false,

      politicas_acesso: false,
    },
  },
  {
    id: 'prof_analista',
    name: 'Analista Estatístico',
    description: 'Acesso a análises, gráficos, dashboards e exportação em CSV/PDF.',
    permissions: {
      colaboradores_alterar_senha: false,
      colaboradores_desativar: false,
      colaboradores_editar: false,
      colaboradores_acesso: false,
      colaboradores_incluir: false,

      analise_acesso: true,
      analise_criar_alterar_excluir_resposta: false,

      importacao_importar_planilha: true,
      importacao_excluir: false,
      importacao_acesso: true,

      meta_criar_alterar_excluir: false,
      meta_acesso: true,

      pesquisa_visualizar_excluidas: false,
      pesquisa_acesso: true,
      pesquisa_criar: false,
      pesquisa_alterar: false,
      pesquisa_excluir: false,
      pesquisa_ouvir_audio: true,
      pesquisa_visualizar_georeferenciamento: true,
      pesquisa_exportar_resultados: true,
      pesquisa_visualizar_inativas: true,
      pesquisa_replicar: false,
      pesquisa_desativar: false,
      pesquisa_acessa_todas_sem_associacao: true,
      pesquisa_alteracao_resposta_espontanea: false,

      respostas_acesso: true,
      respostas_alterar: false,

      home_acesso: true,
      home_visualiza_paineis_superiores: true,
      home_visualiza_conexoes_recentes: true,

      politicas_acesso: false,
    },
  },
];

export const initialCollaborators: Collaborator[] = [
  {
    id: 'colab_1',
    cpf: '123.456.789-00',
    nome: 'Carlos Eduardo Silveira',
    rg: '14.285.910-X',
    dataNascimento: '1985-04-12',
    sexo: 'M',
    login: 'carlos.admin',
    perfilAcessoId: 'prof_admin',
    email: 'carlos.silveira@dataquest.gov.br',
    celular: '(11) 98765-4321',
    nomeContatoCelular: 'Esposa Mariana',
    telefoneFixo: '(11) 3214-5500',
    nomeContatoFixo: 'Escritório Central',
    ativo: true,
    pesquisasVinculadasIds: ['pesq_literarraial_2025', 'pesq_saude_2025'],
    criadoEm: '2025-01-10T10:00:00Z',
  },
  {
    id: 'colab_2',
    cpf: '234.567.890-11',
    nome: 'Mariana Vasconcelos',
    rg: '22.333.444-5',
    dataNascimento: '1990-08-23',
    sexo: 'F',
    login: 'mariana.coord',
    perfilAcessoId: 'prof_coord',
    email: 'mariana.vasconcelos@dataquest.gov.br',
    celular: '(11) 97654-3210',
    nomeContatoCelular: 'Mãe Helena',
    telefoneFixo: '(11) 3214-5502',
    nomeContatoFixo: 'Recepção',
    ativo: true,
    pesquisasVinculadasIds: ['pesq_literarraial_2025'],
    criadoEm: '2025-02-01T14:30:00Z',
  },
  {
    id: 'colab_3',
    cpf: '345.678.901-22',
    nome: 'Rodrigo Fontes Lima',
    rg: '33.444.555-6',
    dataNascimento: '1995-11-05',
    sexo: 'M',
    login: 'rodrigo.pesquisador',
    perfilAcessoId: 'prof_pesq',
    email: 'rodrigo.fontes@dataquest.gov.br',
    celular: '(11) 96543-2109',
    nomeContatoCelular: 'Irmão Lucas',
    telefoneFixo: '(11) 3214-5508',
    nomeContatoFixo: 'Base Operacional',
    ativo: true,
    pesquisasVinculadasIds: ['pesq_literarraial_2025', 'pesq_saude_2025'],
    criadoEm: '2025-02-15T09:00:00Z',
  },
  {
    id: 'colab_4',
    cpf: '456.789.012-33',
    nome: 'Aline Barbosa Ramos',
    rg: '44.555.666-7',
    dataNascimento: '1998-03-17',
    sexo: 'F',
    login: 'aline.pesquisador',
    perfilAcessoId: 'prof_pesq',
    email: 'aline.barbosa@dataquest.gov.br',
    celular: '(11) 95432-1098',
    nomeContatoCelular: 'Pai Roberto',
    telefoneFixo: '',
    nomeContatoFixo: '',
    ativo: true,
    pesquisasVinculadasIds: ['pesq_literarraial_2025'],
    criadoEm: '2025-03-01T11:20:00Z',
  },
  {
    id: 'colab_5',
    cpf: '567.890.123-44',
    nome: 'Fernando Guimarães',
    rg: '55.666.777-8',
    dataNascimento: '1992-07-30',
    sexo: 'M',
    login: 'fernando.analista',
    perfilAcessoId: 'prof_analista',
    email: 'fernando.guimaraes@dataquest.gov.br',
    celular: '(11) 94321-0987',
    nomeContatoCelular: 'Esposa Juliana',
    telefoneFixo: '(11) 3214-5510',
    nomeContatoFixo: 'Depto Estatística',
    ativo: true,
    pesquisasVinculadasIds: ['pesq_literarraial_2025', 'pesq_saude_2025'],
    criadoEm: '2025-03-10T16:45:00Z',
  },
];

export const initialSurveys: Survey[] = [
  {
    id: 'pesq_literarraial_2025',
    codigo: 'LIT-2025-01',
    nome: 'LiterArraial 2025 - Prefeitura',
    descricao: 'Dados sobre a percepção da Feira Literária.',
    status: 'ativa',
    habilitarColetaWeb: true,
    tipoColetaWeb: 'publico',
    colaboradorWebId: 'colab_2',
    pesquisadoresIds: ['colab_1', 'colab_2', 'colab_3', 'colab_4'],
    cicloAtual: 1,
    versao: 1,
    criadaEm: '2025-05-10T08:00:00Z',
    atualizadaEm: '2025-06-01T17:30:00Z',
    perguntas: [
      {
        id: 'q1',
        codigo: 'P01',
        enunciado: 'Você reside no município onde a feira literária está sendo realizada?',
        tipo: 'sim_nao',
        obrigatoria: true,
        ordem: 1,
        opcoes: [
          { id: 'opt_sim', label: 'Sim, sou morador', value: 'Sim' },
          { id: 'opt_nao', label: 'Não, sou visitante/turista', value: 'Não' },
        ],
      },
      {
        id: 'q2',
        codigo: 'P02',
        enunciado: 'Qual a sua faixa etária?',
        tipo: 'multipla_escolha',
        obrigatoria: true,
        ordem: 2,
        opcoes: [
          { id: 'opt_1825', label: '18 a 25 anos', value: '18 a 25 anos' },
          { id: 'opt_2640', label: '26 a 40 anos', value: '26 a 40 anos' },
          { id: 'opt_4160', label: '41 a 60 anos', value: '41 a 60 anos' },
          { id: 'opt_60mais', label: 'Acima de 60 anos', value: 'Acima de 60 anos' },
        ],
      },
      {
        id: 'q3',
        codigo: 'P03',
        enunciado: 'Como você avalia a infraestrutura e acessibilidade do evento?',
        tipo: 'escala_numerica',
        obrigatoria: true,
        ordem: 3,
        escalaMin: 1,
        escalaMax: 5,
        escalaMinLabel: 'Muito Insatisfeito',
        escalaMaxLabel: 'Muito Satisfeito',
      },
      {
        id: 'q4',
        codigo: 'P04',
        enunciado: 'Você realizou compras de livros ou artesanato no local?',
        tipo: 'multipla_escolha',
        obrigatoria: true,
        ordem: 4,
        opcoes: [
          { id: 'opt_compras_sim', label: 'Sim, comprei livros', value: 'Sim' },
          { id: 'opt_compras_nao', label: 'Não comprei nada', value: 'Não' },
          { id: 'opt_compras_ambos', label: 'Comprei livros e outros itens', value: 'Sim, livros e outros' },
        ],
      },
      {
        id: 'q5',
        codigo: 'P05',
        enunciado: 'Qual o principal motivo para não ter realizado compras de livros?',
        tipo: 'multipla_escolha',
        obrigatoria: false,
        ordem: 5,
        opcoes: [
          { id: 'opt_motivo_preco', label: 'Preços elevados', value: 'Preços elevados' },
          { id: 'opt_motivo_titulos', label: 'Não encontrei títulos de interesse', value: 'Falta de títulos' },
          { id: 'opt_motivo_visitante', label: 'Apenas passeando no evento', value: 'Apenas passeando' },
        ],
      },
      {
        id: 'q6',
        codigo: 'P06',
        enunciado: 'Em uma escala de 0 a 10, qual a probabilidade de você indicar a feira a amigos e familiares? (NPS)',
        tipo: 'nps',
        obrigatoria: true,
        ordem: 6,
        escalaMin: 0,
        escalaMax: 10,
        escalaMinLabel: 'Não indicaria',
        escalaMaxLabel: 'Com certeza indicaria',
      },
      {
        id: 'q7',
        codigo: 'P07',
        enunciado: 'Deixe sua crítica, sugestão ou elogio para as próximas edições:',
        tipo: 'texto_aberto',
        obrigatoria: false,
        ordem: 7,
      },
    ],
    regras: [
      {
        id: 'regra_1',
        perguntaOrigemId: 'q4',
        condicao: 'igual',
        valorComparacao: 'Não',
        acao: 'saltar_para',
        perguntaDestinoId: 'q5',
        descricao: 'Se não comprou nada, exibe o motivo da não compra (Q05)',
      },
      {
        id: 'regra_2',
        perguntaOrigemId: 'q4',
        condicao: 'diferente',
        valorComparacao: 'Não',
        acao: 'esconder_pergunta',
        perguntaDestinoId: 'q5',
        descricao: 'Se comprou livros, esconde o motivo de não compra e pula para NPS (Q06)',
      },
    ],
    metas: [
      {
        id: 'meta_1',
        pesquisaId: 'pesq_literarraial_2025',
        perguntaId: 'q1',
        condicao: 'igual',
        resposta: 'Sim',
        quantidadeAlvo: 300,
        quantidadeAtingida: 245,
        ciclo: 'Ciclo 1 - 2025',
      },
      {
        id: 'meta_2',
        pesquisaId: 'pesq_literarraial_2025',
        perguntaId: 'q1',
        condicao: 'igual',
        resposta: 'Não',
        quantidadeAlvo: 150,
        quantidadeAtingida: 132,
        ciclo: 'Ciclo 1 - 2025',
      },
      {
        id: 'meta_3',
        pesquisaId: 'pesq_literarraial_2025',
        perguntaId: 'q2',
        condicao: 'igual',
        resposta: '18 a 25 anos',
        quantidadeAlvo: 120,
        quantidadeAtingida: 114,
        ciclo: 'Ciclo 1 - 2025',
      },
      {
        id: 'meta_4',
        pesquisaId: 'pesq_literarraial_2025',
        perguntaId: 'q4',
        condicao: 'contem',
        resposta: 'Sim',
        quantidadeAlvo: 200,
        quantidadeAtingida: 189,
        ciclo: 'Ciclo 1 - 2025',
      },
    ],
    metasGlobais: [
      {
        id: 'mg_001',
        pesquisaId: 'pesq_literarraial_2025',
        titulo: 'Jovens 18 a 25 anos - Praça da Matriz',
        descricao: 'Amostragem de jovens no perímetro cultural e estandes de livros.',
        criterios: {
          faixaEtaria: '18 a 25 anos',
          sexo: 'Todos',
          bairro: 'Praça da Matriz',
        },
        metaGlobalAlvo: 60,
        metaGlobalAtingida: 48,
        status: 'ativa',
        ciclo: 'Ciclo 1 - 2025',
        criadoEm: '2025-05-12T10:00:00Z',
        atualizadoEm: '2025-06-02T16:00:00Z',
        atribuicoes: [
          {
            pesquisadorId: 'colab_3',
            pesquisadorNome: 'Rodrigo Fontes Lima',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 30,
            cotaAtingida: 24,
            dataAtribuicao: '2025-05-12T10:30:00Z',
          },
          {
            pesquisadorId: 'colab_4',
            pesquisadorNome: 'Aline Barbosa Ramos',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 30,
            cotaAtingida: 24,
            dataAtribuicao: '2025-05-12T10:30:00Z',
          },
        ],
      },
      {
        id: 'mg_002',
        pesquisaId: 'pesq_literarraial_2025',
        titulo: 'Público Feminino - Amostragem Central',
        descricao: 'Garantia de paridade amostral de mulheres com foco no Bairro Centro.',
        criterios: {
          faixaEtaria: 'Todas',
          sexo: 'Feminino',
          bairro: 'Centro',
        },
        metaGlobalAlvo: 80,
        metaGlobalAtingida: 62,
        status: 'ativa',
        ciclo: 'Ciclo 1 - 2025',
        criadoEm: '2025-05-14T11:00:00Z',
        atualizadoEm: '2025-06-02T16:00:00Z',
        atribuicoes: [
          {
            pesquisadorId: 'colab_3',
            pesquisadorNome: 'Rodrigo Fontes Lima',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 40,
            cotaAtingida: 28,
            dataAtribuicao: '2025-05-14T11:15:00Z',
          },
          {
            pesquisadorId: 'colab_4',
            pesquisadorNome: 'Aline Barbosa Ramos',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 40,
            cotaAtingida: 34,
            dataAtribuicao: '2025-05-14T11:15:00Z',
          },
        ],
      },
      {
        id: 'mg_003',
        pesquisaId: 'pesq_literarraial_2025',
        titulo: 'Adultos 41 a 60 anos - Centro & Matriz',
        descricao: 'Amostragem de chefes de família e consumidores de literatura.',
        criterios: {
          faixaEtaria: '41 a 60 anos',
          sexo: 'Todos',
          bairro: 'Centro',
        },
        metaGlobalAlvo: 50,
        metaGlobalAtingida: 50,
        status: 'concluida',
        ciclo: 'Ciclo 1 - 2025',
        criadoEm: '2025-05-15T09:00:00Z',
        atualizadoEm: '2025-06-02T16:00:00Z',
        atribuicoes: [
          {
            pesquisadorId: 'colab_3',
            pesquisadorNome: 'Rodrigo Fontes Lima',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 25,
            cotaAtingida: 25,
            dataAtribuicao: '2025-05-15T09:30:00Z',
          },
          {
            pesquisadorId: 'colab_4',
            pesquisadorNome: 'Aline Barbosa Ramos',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 25,
            cotaAtingida: 25,
            dataAtribuicao: '2025-05-15T09:30:00Z',
          },
        ],
      },
      {
        id: 'mg_004',
        pesquisaId: 'pesq_literarraial_2025',
        titulo: 'Terceira Idade (Acima de 60 anos) - Zona Norte',
        descricao: 'Avaliação de acessibilidade e mobilidade para idosos.',
        criterios: {
          faixaEtaria: 'Acima de 60 anos',
          sexo: 'Todos',
          bairro: 'Zona Norte',
        },
        metaGlobalAlvo: 40,
        metaGlobalAtingida: 18,
        status: 'ativa',
        ciclo: 'Ciclo 1 - 2025',
        criadoEm: '2025-05-18T14:00:00Z',
        atualizadoEm: '2025-06-02T16:00:00Z',
        atribuicoes: [
          {
            pesquisadorId: 'colab_3',
            pesquisadorNome: 'Rodrigo Fontes Lima',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 20,
            cotaAtingida: 9,
            dataAtribuicao: '2025-05-18T14:30:00Z',
          },
          {
            pesquisadorId: 'colab_4',
            pesquisadorNome: 'Aline Barbosa Ramos',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 20,
            cotaAtingida: 9,
            dataAtribuicao: '2025-05-18T14:30:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'pesq_saude_2025',
    codigo: 'SAU-2025-02',
    nome: 'Censo Municipal de Atenção Básica de Saúde',
    descricao: 'Mapeamento de satisfação e tempo de espera nas UBS.',
    status: 'ativa',
    habilitarColetaWeb: false,
    tipoColetaWeb: 'interno',
    colaboradorWebId: 'colab_1',
    pesquisadoresIds: ['colab_1', 'colab_3', 'colab_5'],
    cicloAtual: 1,
    versao: 1,
    criadaEm: '2025-04-15T09:00:00Z',
    atualizadaEm: '2025-05-20T14:10:00Z',
    perguntas: [
      {
        id: 'qs1',
        codigo: 'P01',
        enunciado: 'Qual a sua unidade básica de saúde de referência?',
        tipo: 'multipla_escolha',
        obrigatoria: true,
        ordem: 1,
        opcoes: [
          { id: 'ubs_central', label: 'UBS Central Dr. Paulo', value: 'UBS Central' },
          { id: 'ubs_norte', label: 'UBS Zona Norte', value: 'UBS Zona Norte' },
          { id: 'ubs_sul', label: 'UBS Jardim das Flores', value: 'UBS Sul' },
        ],
      },
      {
        id: 'qs2',
        codigo: 'P02',
        enunciado: 'Você conseguiu agendar sua consulta no mesmo mês?',
        tipo: 'sim_nao',
        obrigatoria: true,
        ordem: 2,
        opcoes: [
          { id: 'opt_sim_s', label: 'Sim', value: 'Sim' },
          { id: 'opt_nao_s', label: 'Não', value: 'Não' },
        ],
      },
      {
        id: 'qs3',
        codigo: 'P03',
        enunciado: 'Qual o grau de satisfação com o atendimento médico?',
        tipo: 'escala_numerica',
        obrigatoria: true,
        ordem: 3,
        escalaMin: 1,
        escalaMax: 5,
        escalaMinLabel: 'Péssimo',
        escalaMaxLabel: 'Excelente',
      },
    ],
    regras: [],
    metas: [
      {
        id: 'meta_s1',
        pesquisaId: 'pesq_saude_2025',
        perguntaId: 'qs2',
        condicao: 'igual',
        resposta: 'Sim',
        quantidadeAlvo: 500,
        quantidadeAtingida: 412,
        ciclo: 'Ciclo 1 - 2025',
      },
    ],
    metasGlobais: [
      {
        id: 'mgs_001',
        pesquisaId: 'pesq_saude_2025',
        titulo: 'Idosos (Acima de 60 anos) - UBS Central',
        descricao: 'Meta prioritária de acolhimento e tempo de espera para pacientes geriátricos.',
        criterios: {
          faixaEtaria: 'Acima de 60 anos',
          sexo: 'Todos',
          bairro: 'UBS Central',
        },
        metaGlobalAlvo: 100,
        metaGlobalAtingida: 75,
        status: 'ativa',
        ciclo: 'Ciclo 1 - 2025',
        criadoEm: '2025-04-20T10:00:00Z',
        atualizadoEm: '2025-05-20T14:10:00Z',
        atribuicoes: [
          {
            pesquisadorId: 'colab_3',
            pesquisadorNome: 'Rodrigo Fontes Lima',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 50,
            cotaAtingida: 42,
            dataAtribuicao: '2025-04-20T10:30:00Z',
          },
          {
            pesquisadorId: 'colab_1',
            pesquisadorNome: 'Carlos Eduardo Silveira',
            perfilAcessoNome: 'Administrador Master',
            cotaAlvo: 50,
            cotaAtingida: 33,
            dataAtribuicao: '2025-04-20T10:30:00Z',
          },
        ],
      },
      {
        id: 'mgs_002',
        pesquisaId: 'pesq_saude_2025',
        titulo: 'Mulheres 26 a 40 anos - UBS Jardim das Flores',
        descricao: 'Saúde da mulher, pré-natal e consultas preventivas.',
        criterios: {
          faixaEtaria: '26 a 40 anos',
          sexo: 'Feminino',
          bairro: 'UBS Sul',
        },
        metaGlobalAlvo: 80,
        metaGlobalAtingida: 45,
        status: 'ativa',
        ciclo: 'Ciclo 1 - 2025',
        criadoEm: '2025-04-22T08:00:00Z',
        atualizadoEm: '2025-05-20T14:10:00Z',
        atribuicoes: [
          {
            pesquisadorId: 'colab_3',
            pesquisadorNome: 'Rodrigo Fontes Lima',
            perfilAcessoNome: 'Pesquisador de Campo',
            cotaAlvo: 40,
            cotaAtingida: 25,
            dataAtribuicao: '2025-04-22T08:30:00Z',
          },
          {
            pesquisadorId: 'colab_5',
            pesquisadorNome: 'Fernando Guimarães',
            perfilAcessoNome: 'Analista Estatístico',
            cotaAlvo: 40,
            cotaAtingida: 20,
            dataAtribuicao: '2025-04-22T08:30:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'pesq_inativa_demo',
    codigo: 'HAB-2024-04',
    nome: 'Diagnóstico Habitacional 2024 (Ciclo Anterior)',
    descricao: 'Levantamento concluído do programa de habitação popular.',
    status: 'inativa',
    habilitarColetaWeb: true,
    tipoColetaWeb: 'publico',
    pesquisadoresIds: ['colab_1', 'colab_2'],
    cicloAtual: 2,
    versao: 2,
    criadaEm: '2024-06-01T10:00:00Z',
    atualizadaEm: '2024-12-15T18:00:00Z',
    perguntas: [],
    regras: [],
    metas: [],
  },
];

export const initialSubmissions: InterviewSubmission[] = [
  {
    id: 'sub_001',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-06-02T14:32:15',
    status: 'concluida',
    respostas: [
      {
        perguntaId: 'q1',
        perguntaCodigo: 'P01',
        perguntaEnunciado: 'Você reside no município onde a feira literária está sendo realizada?',
        resposta: 'Sim',
      },
      {
        perguntaId: 'q2',
        perguntaCodigo: 'P02',
        perguntaEnunciado: 'Qual a sua faixa etária?',
        resposta: '26 a 40 anos',
      },
      {
        perguntaId: 'q3',
        perguntaCodigo: 'P03',
        perguntaEnunciado: 'Como você avalia a infraestrutura e acessibilidade do evento?',
        resposta: '5',
      },
      {
        perguntaId: 'q4',
        perguntaCodigo: 'P04',
        perguntaEnunciado: 'Você realizou compras de livros ou artesanato no local?',
        resposta: 'Sim',
      },
      {
        perguntaId: 'q6',
        perguntaCodigo: 'P06',
        perguntaEnunciado: 'Em uma escala de 0 a 10, qual a probabilidade de você indicar a feira a amigos e familiares? (NPS)',
        resposta: '10',
      },
      {
        perguntaId: 'q7',
        perguntaCodigo: 'P07',
        perguntaEnunciado: 'Deixe sua crítica, sugestão ou elogio para as próximas edições:',
        resposta: 'Organização impecável, excelente curadoria de autores nacionais!',
      },
    ],
    geolocalizacao: {
      latitude: -23.55052,
      longitude: -46.633308,
      bairro: 'Centro Histórico',
      cidade: 'São Paulo - SP',
    },
    audioGravacao: {
      duracaoSegundos: 142,
      tamanhoKb: 890,
      nomeArquivo: 'gravacao_entrevista_001_audio.wav',
      transcricaoTrecho: 'Entrevistado confirma moradia no centro e elogia a acessibilidade e estandes.',
    },
    respostasAlteradasPeloAdmin: false,
  },
  {
    id: 'sub_002',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_4',
    pesquisadorNome: 'Aline Barbosa Ramos',
    dataHora: '2025-06-02T15:10:44',
    status: 'concluida',
    respostas: [
      {
        perguntaId: 'q1',
        perguntaCodigo: 'P01',
        perguntaEnunciado: 'Você reside no município onde a feira literária está sendo realizada?',
        resposta: 'Não',
      },
      {
        perguntaId: 'q2',
        perguntaCodigo: 'P02',
        perguntaEnunciado: 'Qual a sua faixa etária?',
        resposta: '18 a 25 anos',
      },
      {
        perguntaId: 'q3',
        perguntaCodigo: 'P03',
        perguntaEnunciado: 'Como você avalia a infraestrutura e acessibilidade do evento?',
        resposta: '4',
      },
      {
        perguntaId: 'q4',
        perguntaCodigo: 'P04',
        perguntaEnunciado: 'Você realizou compras de livros ou artesanato no local?',
        resposta: 'Não',
      },
      {
        perguntaId: 'q5',
        perguntaCodigo: 'P05',
        perguntaEnunciado: 'Qual o principal motivo para não ter realizado compras de livros?',
        resposta: 'Preços elevados',
      },
      {
        perguntaId: 'q6',
        perguntaCodigo: 'P06',
        perguntaEnunciado: 'Em uma escala de 0 a 10, qual a probabilidade de você indicar a feira a amigos e familiares? (NPS)',
        resposta: '8',
      },
      {
        perguntaId: 'q7',
        perguntaCodigo: 'P07',
        perguntaEnunciado: 'Deixe sua crítica, sugestão ou elogio para as próximas edições:',
        resposta: 'Gostei muito das oficinas, mas os livros poderiam ter mais descontos de feira.',
      },
    ],
    geolocalizacao: {
      latitude: -23.5518,
      longitude: -46.6345,
      bairro: 'Praça da Matriz',
      cidade: 'São Paulo - SP',
    },
    audioGravacao: {
      duracaoSegundos: 95,
      tamanhoKb: 610,
      nomeArquivo: 'gravacao_entrevista_002_audio.wav',
      transcricaoTrecho: 'Jovem visitante universitária comenta sobre preços e interesse em palestras.',
    },
    respostasAlteradasPeloAdmin: false,
  },
  {
    id: 'sub_003',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-06-02T16:05:20',
    status: 'concluida',
    respostas: [
      {
        perguntaId: 'q1',
        perguntaCodigo: 'P01',
        perguntaEnunciado: 'Você reside no município onde a feira literária está sendo realizada?',
        resposta: 'Sim',
      },
      {
        perguntaId: 'q2',
        perguntaCodigo: 'P02',
        perguntaEnunciado: 'Qual a sua faixa etária?',
        resposta: '41 a 60 anos',
      },
      {
        perguntaId: 'q3',
        perguntaCodigo: 'P03',
        perguntaEnunciado: 'Como você avalia a infraestrutura e acessibilidade do evento?',
        resposta: '5',
      },
      {
        perguntaId: 'q4',
        perguntaCodigo: 'P04',
        perguntaEnunciado: 'Você realizou compras de livros ou artesanato no local?',
        resposta: 'Sim, livros e outros',
      },
      {
        perguntaId: 'q6',
        perguntaCodigo: 'P06',
        perguntaEnunciado: 'Em uma escala de 0 a 10, qual a probabilidade de você indicar a feira a amigos e familiares? (NPS)',
        resposta: '9',
      },
      {
        perguntaId: 'q7',
        perguntaCodigo: 'P07',
        perguntaEnunciado: 'Deixe sua crítica, sugestão ou elogio para as próximas edições:',
        resposta: 'Excelente praça de alimentação e banheiros bem cuidados.',
      },
    ],
    geolocalizacao: {
      latitude: -23.5492,
      longitude: -46.6321,
      bairro: 'Pavilhão das Letras',
      cidade: 'São Paulo - SP',
    },
    audioGravacao: {
      duracaoSegundos: 165,
      tamanhoKb: 980,
      nomeArquivo: 'gravacao_entrevista_003_audio.wav',
      transcricaoTrecho: 'Entrevistado acompanhado da família comprou 3 títulos infantis e 1 romance.',
    },
    respostasAlteradasPeloAdmin: false,
  },
  {
    id: 'sub_004',
    codigoPesquisa: 'SAU-2025-02',
    pesquisaId: 'pesq_saude_2025',
    pesquisaNome: 'Censo Municipal de Atenção Básica de Saúde',
    pesquisadorId: 'colab_1',
    pesquisadorNome: 'Carlos Eduardo Silveira',
    dataHora: '2025-06-02T16:40:11',
    status: 'concluida',
    respostas: [
      {
        perguntaId: 'qs1',
        perguntaCodigo: 'P01',
        perguntaEnunciado: 'Qual a sua unidade básica de saúde de referência?',
        resposta: 'UBS Central',
      },
      {
        perguntaId: 'qs2',
        perguntaCodigo: 'P02',
        perguntaEnunciado: 'Você conseguiu agendar sua consulta no mesmo mês?',
        resposta: 'Sim',
      },
      {
        perguntaId: 'qs3',
        perguntaCodigo: 'P03',
        perguntaEnunciado: 'Qual o grau de satisfação com o atendimento médico?',
        resposta: '4',
      },
    ],
    geolocalizacao: {
      latitude: -23.553,
      longitude: -46.637,
      bairro: 'Bela Vista',
      cidade: 'São Paulo - SP',
    },
    audioGravacao: {
      duracaoSegundos: 80,
      tamanhoKb: 450,
      nomeArquivo: 'gravacao_entrevista_sau_001.wav',
      transcricaoTrecho: 'Paciente relata bom atendimento na triagem de enfermagem.',
    },
    respostasAlteradasPeloAdmin: false,
  },
  // Submissions for multi-day tracking verification
  {
    id: 'sub_005',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-05-26T10:15:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '18 a 25 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '5' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '10' }
    ]
  },
  {
    id: 'sub_006',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_4',
    pesquisadorNome: 'Aline Barbosa Ramos',
    dataHora: '2025-05-26T14:40:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '26 a 40 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '4' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '9' }
    ]
  },
  {
    id: 'sub_007',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-05-27T09:20:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Não' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '41 a 60 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '4' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '8' }
    ]
  },
  {
    id: 'sub_008',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_4',
    pesquisadorNome: 'Aline Barbosa Ramos',
    dataHora: '2025-05-27T11:50:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: 'Mais de 60 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '5' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '10' }
    ]
  },
  {
    id: 'sub_009',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-05-27T16:10:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '26 a 40 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '5' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '9' }
    ]
  },
  {
    id: 'sub_010',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_4',
    pesquisadorNome: 'Aline Barbosa Ramos',
    dataHora: '2025-05-28T10:00:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '18 a 25 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '4' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '8' }
    ]
  },
  {
    id: 'sub_011',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-05-28T14:30:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '26 a 40 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '5' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '10' }
    ]
  },
  {
    id: 'sub_012',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_4',
    pesquisadorNome: 'Aline Barbosa Ramos',
    dataHora: '2025-05-29T11:15:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Não' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '41 a 60 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '4' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '9' }
    ]
  },
  {
    id: 'sub_013',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-05-29T15:45:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '18 a 25 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '5' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '10' }
    ]
  },
  {
    id: 'sub_014',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_4',
    pesquisadorNome: 'Aline Barbosa Ramos',
    dataHora: '2025-05-30T10:40:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '26 a 40 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '5' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '9' }
    ]
  },
  {
    id: 'sub_015',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-05-30T16:20:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '41 a 60 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '4' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '8' }
    ]
  },
  {
    id: 'sub_016',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_4',
    pesquisadorNome: 'Aline Barbosa Ramos',
    dataHora: '2025-05-31T09:30:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '18 a 25 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '5' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '10' }
    ]
  },
  {
    id: 'sub_017',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-05-31T14:10:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '26 a 40 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '4' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '9' }
    ]
  },
  {
    id: 'sub_018',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_4',
    pesquisadorNome: 'Aline Barbosa Ramos',
    dataHora: '2025-06-01T10:00:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: 'Mais de 60 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '5' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '10' }
    ]
  },
  {
    id: 'sub_019',
    codigoPesquisa: 'LIT-2025-01',
    pesquisaId: 'pesq_literarraial_2025',
    pesquisaNome: 'LiterArraial 2025 - Prefeitura',
    pesquisadorId: 'colab_3',
    pesquisadorNome: 'Rodrigo Fontes Lima',
    dataHora: '2025-06-01T15:30:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'q1', perguntaCodigo: 'P01', perguntaEnunciado: 'Você reside no município?', resposta: 'Sim' },
      { perguntaId: 'q2', perguntaCodigo: 'P02', perguntaEnunciado: 'Faixa etária', resposta: '26 a 40 anos' },
      { perguntaId: 'q3', perguntaCodigo: 'P03', perguntaEnunciado: 'Avaliação de infraestrutura', resposta: '5' },
      { perguntaId: 'q6', perguntaCodigo: 'P06', perguntaEnunciado: 'NPS', resposta: '9' }
    ]
  },
  // Saúde Municipal Submissions
  {
    id: 'sub_sau_002',
    codigoPesquisa: 'SAU-2025-02',
    pesquisaId: 'pesq_saude_2025',
    pesquisaNome: 'Censo Municipal de Atenção Básica de Saúde',
    pesquisadorId: 'colab_1',
    pesquisadorNome: 'Carlos Eduardo Silveira',
    dataHora: '2025-05-27T08:30:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'qs1', perguntaCodigo: 'P01', perguntaEnunciado: 'Unidade de referência', resposta: 'UBS Jardim das Flores' },
      { perguntaId: 'qs2', perguntaCodigo: 'P02', perguntaEnunciado: 'Agendamento no mesmo mês', resposta: 'Sim' },
      { perguntaId: 'qs3', perguntaCodigo: 'P03', perguntaEnunciado: 'Satisfação atendimento', resposta: '5' }
    ]
  },
  {
    id: 'sub_sau_003',
    codigoPesquisa: 'SAU-2025-02',
    pesquisaId: 'pesq_saude_2025',
    pesquisaNome: 'Censo Municipal de Atenção Básica de Saúde',
    pesquisadorId: 'colab_2',
    pesquisadorNome: 'Mariana Vasconcelos',
    dataHora: '2025-05-28T09:15:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'qs1', perguntaCodigo: 'P01', perguntaEnunciado: 'Unidade de referência', resposta: 'UBS Central' },
      { perguntaId: 'qs2', perguntaCodigo: 'P02', perguntaEnunciado: 'Agendamento no mesmo mês', resposta: 'Não' },
      { perguntaId: 'qs3', perguntaCodigo: 'P03', perguntaEnunciado: 'Satisfação atendimento', resposta: '3' }
    ]
  },
  {
    id: 'sub_sau_004',
    codigoPesquisa: 'SAU-2025-02',
    pesquisaId: 'pesq_saude_2025',
    pesquisaNome: 'Censo Municipal de Atenção Básica de Saúde',
    pesquisadorId: 'colab_1',
    pesquisadorNome: 'Carlos Eduardo Silveira',
    dataHora: '2025-05-29T11:00:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'qs1', perguntaCodigo: 'P01', perguntaEnunciado: 'Unidade de referência', resposta: 'UBS Vila Esperança' },
      { perguntaId: 'qs2', perguntaCodigo: 'P02', perguntaEnunciado: 'Agendamento no mesmo mês', resposta: 'Sim' },
      { perguntaId: 'qs3', perguntaCodigo: 'P03', perguntaEnunciado: 'Satisfação atendimento', resposta: '5' }
    ]
  },
  {
    id: 'sub_sau_005',
    codigoPesquisa: 'SAU-2025-02',
    pesquisaId: 'pesq_saude_2025',
    pesquisaNome: 'Censo Municipal de Atenção Básica de Saúde',
    pesquisadorId: 'colab_2',
    pesquisadorNome: 'Mariana Vasconcelos',
    dataHora: '2025-05-30T14:20:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'qs1', perguntaCodigo: 'P01', perguntaEnunciado: 'Unidade de referência', resposta: 'UBS Central' },
      { perguntaId: 'qs2', perguntaCodigo: 'P02', perguntaEnunciado: 'Agendamento no mesmo mês', resposta: 'Sim' },
      { perguntaId: 'qs3', perguntaCodigo: 'P03', perguntaEnunciado: 'Satisfação atendimento', resposta: '4' }
    ]
  },
  {
    id: 'sub_sau_006',
    codigoPesquisa: 'SAU-2025-02',
    pesquisaId: 'pesq_saude_2025',
    pesquisaNome: 'Censo Municipal de Atenção Básica de Saúde',
    pesquisadorId: 'colab_1',
    pesquisadorNome: 'Carlos Eduardo Silveira',
    dataHora: '2025-05-31T10:45:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'qs1', perguntaCodigo: 'P01', perguntaEnunciado: 'Unidade de referência', resposta: 'UBS Central' },
      { perguntaId: 'qs2', perguntaCodigo: 'P02', perguntaEnunciado: 'Agendamento no mesmo mês', resposta: 'Sim' },
      { perguntaId: 'qs3', perguntaCodigo: 'P03', perguntaEnunciado: 'Satisfação atendimento', resposta: '5' }
    ]
  },
  {
    id: 'sub_sau_007',
    codigoPesquisa: 'SAU-2025-02',
    pesquisaId: 'pesq_saude_2025',
    pesquisaNome: 'Censo Municipal de Atenção Básica de Saúde',
    pesquisadorId: 'colab_2',
    pesquisadorNome: 'Mariana Vasconcelos',
    dataHora: '2025-06-01T11:30:00',
    status: 'concluida',
    respostas: [
      { perguntaId: 'qs1', perguntaCodigo: 'P01', perguntaEnunciado: 'Unidade de referência', resposta: 'UBS Bela Vista' },
      { perguntaId: 'qs2', perguntaCodigo: 'P02', perguntaEnunciado: 'Agendamento no mesmo mês', resposta: 'Sim' },
      { perguntaId: 'qs3', perguntaCodigo: 'P03', perguntaEnunciado: 'Satisfação atendimento', resposta: '4' }
    ]
  }
];

export const initialConnections: RecentConnection[] = [
  {
    id: 'conn_1',
    usuario: 'carlos.admin (Carlos Eduardo)',
    perfil: 'Administrador Master',
    ip: '189.40.112.54',
    dataHora: '02/06/2025 17:15:32',
    navegador: 'Chrome 125 / Linux x86_64',
    status: 'sucesso',
  },
  {
    id: 'conn_2',
    usuario: 'mariana.coord (Mariana V.)',
    perfil: 'Coordenador de Campo',
    ip: '177.102.88.19',
    dataHora: '02/06/2025 16:50:12',
    navegador: 'Edge 124 / Windows 11',
    status: 'sucesso',
  },
  {
    id: 'conn_3',
    usuario: 'rodrigo.pesquisador (Rodrigo F.)',
    perfil: 'Pesquisador de Campo',
    ip: '191.22.45.101',
    dataHora: '02/06/2025 16:04:02',
    navegador: 'Mobile Safari / iOS 17.5',
    status: 'sucesso',
  },
  {
    id: 'conn_4',
    usuario: 'aline.pesquisador (Aline B.)',
    perfil: 'Pesquisador de Campo',
    ip: '179.184.21.7',
    dataHora: '02/06/2025 15:09:18',
    navegador: 'Chrome Mobile / Android 14',
    status: 'sucesso',
  },
  {
    id: 'conn_5',
    usuario: 'usuario.desconhecido',
    perfil: 'Não autenticado',
    ip: '45.12.98.11',
    dataHora: '02/06/2025 12:45:00',
    navegador: 'Firefox 126 / macOS',
    status: 'bloqueado',
  },
];

export const initialImports: ExternalImport[] = [
  {
    id: 'imp_01',
    nomeArquivo: 'Censo_Literario_Dados_Preliminares_2025.csv',
    pesquisaId: 'pesq_literarraial_2025',
    dataImportacao: '2025-05-28 14:22:10',
    totalRegistros: 140,
    colunas: ['cpf_anonimizado', 'residente_municipio', 'faixa_etaria', 'nota_infra', 'comprou_livro', 'nps'],
    status: 'concluido',
  },
  {
    id: 'imp_02',
    nomeArquivo: 'UBS_Amostragem_Piloto_Maio.xlsx',
    pesquisaId: 'pesq_saude_2025',
    dataImportacao: '2025-05-15 09:10:44',
    totalRegistros: 85,
    colunas: ['unidade_ubs', 'agendamento_mesmo_mes', 'grau_satisfacao'],
    status: 'concluido',
  },
];

export const initialAuditLogs: ActionAuditLog[] = [
  {
    id: 'log_001',
    categoria: 'RESPOSTA',
    tipoAcao: 'EDICAO_RESPOSTA',
    tituloAcao: 'Edição de Resposta em Coleta',
    descricaoDetalhada: 'Retificação administrativa de resposta no formulário de entrevista #INT-8831 (LiterArraial 2025).',
    autor: {
      id: 'colab_01',
      nome: 'Carlos Eduardo Silva',
      login: 'admin',
      perfil: 'Administrador Master',
      ip: '189.40.72.19',
    },
    alvo: {
      tipo: 'resposta',
      id: 'sub_001',
      identificador: 'Coleta #INT-8831',
      nome: 'LiterArraial 2025 - Prefeitura',
    },
    alteracoes: [
      {
        campo: 'P03 - Você adquiriu algum livro durante o evento?',
        rotulo: 'Questão P03',
        valorAnterior: 'Não',
        valorNovo: 'Sim (1 a 2 livros)',
      },
    ],
    motivoConformidade: 'Correção de erro de digitação do pesquisador em campo após conferência do áudio da gravação e validação com o supervisor.',
    timestamp: '2026-09-02T16:42:15.000Z',
    hashIntegridade: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    statusConformidade: 'conforme',
  },
  {
    id: 'log_002',
    categoria: 'PESQUISA',
    tipoAcao: 'EDICAO_PESQUISA',
    tituloAcao: 'Alteração de Configuração de Pesquisa',
    descricaoDetalhada: 'Habilitação da Coleta Web Pública e inclusão da regra condicional de salto para questão P05.',
    autor: {
      id: 'colab_01',
      nome: 'Carlos Eduardo Silva',
      login: 'admin',
      perfil: 'Administrador Master',
      ip: '189.40.72.19',
    },
    alvo: {
      tipo: 'pesquisa',
      id: 'pesq_literarraial_2025',
      identificador: 'PESQ-2025-01',
      nome: 'LiterArraial 2025 - Prefeitura',
    },
    alteracoes: [
      {
        campo: 'habilitarColetaWeb',
        rotulo: 'Coleta Web',
        valorAnterior: 'Inativo (false)',
        valorNovo: 'Ativo (true - Público)',
      },
      {
        campo: 'regras',
        rotulo: 'Regras Condicionais',
        valorAnterior: '0 regras',
        valorNovo: '1 regra (P01 = Não -> Saltar para P05)',
      },
    ],
    motivoConformidade: 'Abertura do canal de coleta web para munícipes e otimização do roteiro de perguntas conforme protocolo da Secretaria de Cultura.',
    timestamp: '2026-09-01T14:15:30.000Z',
    hashIntegridade: '7d793037a0760186574b0282f2f435e7b1e7a6acc941e07400eeb7e12075487a',
    statusConformidade: 'conforme',
  },
  {
    id: 'log_003',
    categoria: 'PESQUISA',
    tipoAcao: 'REPLICACAO_PESQUISA',
    tituloAcao: 'Replicação de Pesquisa para Novo Ciclo',
    descricaoDetalhada: 'Pesquisa duplicada para o Ciclo 2 preservando estrutura de questionário e reiniciando metas de amostragem.',
    autor: {
      id: 'colab_02',
      nome: 'Mariana Costa Oliveira',
      login: 'mariana.coord',
      perfil: 'Coordenador de Campo',
      ip: '201.86.115.44',
    },
    alvo: {
      tipo: 'pesquisa',
      id: 'pesq_literarraial_2025_c2',
      identificador: 'PESQ-2025-01-C2',
      nome: 'LiterArraial 2025 - Prefeitura (Ciclo 2)',
    },
    alteracoes: [
      {
        campo: 'cicloAtual',
        rotulo: 'Ciclo',
        valorAnterior: 'Ciclo 1',
        valorNovo: 'Ciclo 2',
      },
      {
        campo: 'versao',
        rotulo: 'Versão',
        valorAnterior: '1',
        valorNovo: '2',
      },
    ],
    motivoConformidade: 'Abertura da segunda fase de coleta após atingimento das metas amostrais da primeira fase.',
    timestamp: '2026-08-30T11:00:22.000Z',
    hashIntegridade: 'f454f0a3952d7e00858e72ef78385adadcdad3f2a89327ee0cf075be8c0762cf',
    statusConformidade: 'conforme',
  },
  {
    id: 'log_004',
    categoria: 'RESPOSTA',
    tipoAcao: 'EDICAO_RESPOSTA',
    tituloAcao: 'Ajuste de Dado Espontâneo em Resposta',
    descricaoDetalhada: 'Adequação da transcrição da resposta aberta na coleta #INT-8833 (UBS São Francisco).',
    autor: {
      id: 'colab_01',
      nome: 'Carlos Eduardo Silva',
      login: 'admin',
      perfil: 'Administrador Master',
      ip: '189.40.72.19',
    },
    alvo: {
      tipo: 'resposta',
      id: 'sub_003',
      identificador: 'Coleta #INT-8833',
      nome: 'Avaliação dos Serviços de Saúde - UBS',
    },
    alteracoes: [
      {
        campo: 'P03 - Sugestões de Melhoria',
        rotulo: 'Resposta Espontânea',
        valorAnterior: 'falta remdio na farmacia',
        valorNovo: 'Falta de medicamentos de uso contínuo na farmácia básica',
      },
    ],
    motivoConformidade: 'Padronização ortográfica para codificação temática na análise quanti-qualitativa, sem alteração de sentido semântico.',
    timestamp: '2026-08-28T09:20:00.000Z',
    hashIntegridade: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    statusConformidade: 'conforme',
  },
  {
    id: 'log_005',
    categoria: 'PESQUISA',
    tipoAcao: 'STATUS_PESQUISA',
    tituloAcao: 'Alteração de Status da Pesquisa',
    descricaoDetalhada: 'Pesquisa alterada de Inativa para Ativa para início das coletas dos agentes de campo.',
    autor: {
      id: 'colab_01',
      nome: 'Carlos Eduardo Silva',
      login: 'admin',
      perfil: 'Administrador Master',
      ip: '189.40.72.19',
    },
    alvo: {
      tipo: 'pesquisa',
      id: 'pesq_saude_2025',
      identificador: 'PESQ-2025-02',
      nome: 'Avaliação dos Serviços de Saúde - UBS',
    },
    alteracoes: [
      {
        campo: 'status',
        rotulo: 'Status Operacional',
        valorAnterior: 'inativa',
        valorNovo: 'ativa',
      },
    ],
    motivoConformidade: 'Validação jurídica e ética do instrumento de pesquisa concluída pela Coordenadoria de Saúde.',
    timestamp: '2026-08-25T08:00:00.000Z',
    hashIntegridade: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    statusConformidade: 'conforme',
  },
  {
    id: 'log_006',
    categoria: 'PESQUISA',
    tipoAcao: 'CRIACAO_PESQUISA',
    tituloAcao: 'Criação de Novo Instrumento de Pesquisa',
    descricaoDetalhada: 'Cadastro inicial do questionário LiterArraial 2025 com 5 perguntas, regras e vinculação de 4 pesquisadores.',
    autor: {
      id: 'colab_01',
      nome: 'Carlos Eduardo Silva',
      login: 'admin',
      perfil: 'Administrador Master',
      ip: '189.40.72.19',
    },
    alvo: {
      tipo: 'pesquisa',
      id: 'pesq_literarraial_2025',
      identificador: 'PESQ-2025-01',
      nome: 'LiterArraial 2025 - Prefeitura',
    },
    alteracoes: [
      {
        campo: 'nome',
        rotulo: 'Nome',
        valorNovo: 'LiterArraial 2025 - Prefeitura',
      },
      {
        campo: 'perguntas',
        rotulo: 'Perguntas Cadastradas',
        valorNovo: '5 perguntas configuradas',
      },
    ],
    motivoConformidade: 'Abertura oficial de edital de avaliação de satisfação pública do evento municipal.',
    timestamp: '2026-08-20T10:00:00.000Z',
    hashIntegridade: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    statusConformidade: 'conforme',
  },
];
